### ISSUE TITLE
Highlight cross-character weapon balancing

### ISSUE THREAD

**Issue by baptr** [legion0/llbalancer#1]
I noticed a scenario today where one character could be balanced up by acquiring an at-level weapon on another character. It would be nice if the sheet could call that out somehow:

![image](https://user-images.githubusercontent.com/1522777/84729241-11d68900-af48-11ea-99e6-6ace78890c63.png)

**Comment by legion0** [comment]
In that example screenshot do you mean that getting a 1051 power weapon on your hunter is "at level" and would balance out your Titan that has 1 required point?

**Comment by baptr** [comment]
Yeah, exactly.

**Comment by legion0** [comment]
Fixed
